// Code generated by MockGen. DO NOT EDIT.
// Source: ../ofm-common/proto/orderwrite/v1/orderwrite_grpc.pb.go
//
// Generated by this command:
//
//	mockgen -source=../ofm-common/proto/orderwrite/v1/orderwrite_grpc.pb.go -destination=internal/infra/order/grpc/orderwrite_client_mock_test.go -package=grpc
//

// Package grpc is a generated GoMock package.
package grpc

import (
	context "context"
	reflect "reflect"

	v1 "github.com/ofm-microservices/ofm-common/proto/orderwrite/v1"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockOrderWriteServiceClient is a mock of OrderWriteServiceClient interface.
type MockOrderWriteServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockOrderWriteServiceClientMockRecorder
	isgomock struct{}
}

// MockOrderWriteServiceClientMockRecorder is the mock recorder for MockOrderWriteServiceClient.
type MockOrderWriteServiceClientMockRecorder struct {
	mock *MockOrderWriteServiceClient
}

// NewMockOrderWriteServiceClient creates a new mock instance.
func NewMockOrderWriteServiceClient(ctrl *gomock.Controller) *MockOrderWriteServiceClient {
	mock := &MockOrderWriteServiceClient{ctrl: ctrl}
	mock.recorder = &MockOrderWriteServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderWriteServiceClient) EXPECT() *MockOrderWriteServiceClientMockRecorder {
	return m.recorder
}

// AttachFileToOrder mocks base method.
func (m *MockOrderWriteServiceClient) AttachFileToOrder(ctx context.Context, in *v1.AttachFileToOrderRequest, opts ...grpc.CallOption) (*v1.AttachFileToOrderResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AttachFileToOrder", varargs...)
	ret0, _ := ret[0].(*v1.AttachFileToOrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AttachFileToOrder indicates an expected call of AttachFileToOrder.
func (mr *MockOrderWriteServiceClientMockRecorder) AttachFileToOrder(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttachFileToOrder", reflect.TypeOf((*MockOrderWriteServiceClient)(nil).AttachFileToOrder), varargs...)
}

// CreateDraftOrder mocks base method.
func (m *MockOrderWriteServiceClient) CreateDraftOrder(ctx context.Context, in *v1.CreateDraftOrderRequest, opts ...grpc.CallOption) (*v1.CreateDraftOrderResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateDraftOrder", varargs...)
	ret0, _ := ret[0].(*v1.CreateDraftOrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDraftOrder indicates an expected call of CreateDraftOrder.
func (mr *MockOrderWriteServiceClientMockRecorder) CreateDraftOrder(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDraftOrder", reflect.TypeOf((*MockOrderWriteServiceClient)(nil).CreateDraftOrder), varargs...)
}

// GetOrderLifecycleSnapshot mocks base method.
func (m *MockOrderWriteServiceClient) GetOrderLifecycleSnapshot(ctx context.Context, in *v1.GetOrderLifecycleSnapshotRequest, opts ...grpc.CallOption) (*v1.GetOrderLifecycleSnapshotResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetOrderLifecycleSnapshot", varargs...)
	ret0, _ := ret[0].(*v1.GetOrderLifecycleSnapshotResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderLifecycleSnapshot indicates an expected call of GetOrderLifecycleSnapshot.
func (mr *MockOrderWriteServiceClientMockRecorder) GetOrderLifecycleSnapshot(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderLifecycleSnapshot", reflect.TypeOf((*MockOrderWriteServiceClient)(nil).GetOrderLifecycleSnapshot), varargs...)
}

// GetOrderPaymentSnapshot mocks base method.
func (m *MockOrderWriteServiceClient) GetOrderPaymentSnapshot(ctx context.Context, in *v1.GetOrderPaymentSnapshotRequest, opts ...grpc.CallOption) (*v1.GetOrderPaymentSnapshotResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetOrderPaymentSnapshot", varargs...)
	ret0, _ := ret[0].(*v1.GetOrderPaymentSnapshotResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderPaymentSnapshot indicates an expected call of GetOrderPaymentSnapshot.
func (mr *MockOrderWriteServiceClientMockRecorder) GetOrderPaymentSnapshot(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderPaymentSnapshot", reflect.TypeOf((*MockOrderWriteServiceClient)(nil).GetOrderPaymentSnapshot), varargs...)
}

// MarkOrderCompleted mocks base method.
func (m *MockOrderWriteServiceClient) MarkOrderCompleted(ctx context.Context, in *v1.MarkOrderCompletedRequest, opts ...grpc.CallOption) (*v1.MarkOrderCompletedResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "MarkOrderCompleted", varargs...)
	ret0, _ := ret[0].(*v1.MarkOrderCompletedResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkOrderCompleted indicates an expected call of MarkOrderCompleted.
func (mr *MockOrderWriteServiceClientMockRecorder) MarkOrderCompleted(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkOrderCompleted", reflect.TypeOf((*MockOrderWriteServiceClient)(nil).MarkOrderCompleted), varargs...)
}

// MarkOrderFunded mocks base method.
func (m *MockOrderWriteServiceClient) MarkOrderFunded(ctx context.Context, in *v1.MarkOrderFundedRequest, opts ...grpc.CallOption) (*v1.MarkOrderFundedResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "MarkOrderFunded", varargs...)
	ret0, _ := ret[0].(*v1.MarkOrderFundedResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkOrderFunded indicates an expected call of MarkOrderFunded.
func (mr *MockOrderWriteServiceClientMockRecorder) MarkOrderFunded(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkOrderFunded", reflect.TypeOf((*MockOrderWriteServiceClient)(nil).MarkOrderFunded), varargs...)
}

// MarkPaymentFailed mocks base method.
func (m *MockOrderWriteServiceClient) MarkPaymentFailed(ctx context.Context, in *v1.MarkPaymentFailedRequest, opts ...grpc.CallOption) (*v1.MarkPaymentFailedResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "MarkPaymentFailed", varargs...)
	ret0, _ := ret[0].(*v1.MarkPaymentFailedResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkPaymentFailed indicates an expected call of MarkPaymentFailed.
func (mr *MockOrderWriteServiceClientMockRecorder) MarkPaymentFailed(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkPaymentFailed", reflect.TypeOf((*MockOrderWriteServiceClient)(nil).MarkPaymentFailed), varargs...)
}

// MarkPaymentPending mocks base method.
func (m *MockOrderWriteServiceClient) MarkPaymentPending(ctx context.Context, in *v1.MarkPaymentPendingRequest, opts ...grpc.CallOption) (*v1.MarkPaymentPendingResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "MarkPaymentPending", varargs...)
	ret0, _ := ret[0].(*v1.MarkPaymentPendingResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkPaymentPending indicates an expected call of MarkPaymentPending.
func (mr *MockOrderWriteServiceClientMockRecorder) MarkPaymentPending(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkPaymentPending", reflect.TypeOf((*MockOrderWriteServiceClient)(nil).MarkPaymentPending), varargs...)
}

// MarkReleaseFailed mocks base method.
func (m *MockOrderWriteServiceClient) MarkReleaseFailed(ctx context.Context, in *v1.MarkReleaseFailedRequest, opts ...grpc.CallOption) (*v1.MarkReleaseFailedResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "MarkReleaseFailed", varargs...)
	ret0, _ := ret[0].(*v1.MarkReleaseFailedResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkReleaseFailed indicates an expected call of MarkReleaseFailed.
func (mr *MockOrderWriteServiceClientMockRecorder) MarkReleaseFailed(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkReleaseFailed", reflect.TypeOf((*MockOrderWriteServiceClient)(nil).MarkReleaseFailed), varargs...)
}

// MarkReleasePending mocks base method.
func (m *MockOrderWriteServiceClient) MarkReleasePending(ctx context.Context, in *v1.MarkReleasePendingRequest, opts ...grpc.CallOption) (*v1.MarkReleasePendingResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "MarkReleasePending", varargs...)
	ret0, _ := ret[0].(*v1.MarkReleasePendingResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkReleasePending indicates an expected call of MarkReleasePending.
func (mr *MockOrderWriteServiceClientMockRecorder) MarkReleasePending(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkReleasePending", reflect.TypeOf((*MockOrderWriteServiceClient)(nil).MarkReleasePending), varargs...)
}

// OpenDispute mocks base method.
func (m *MockOrderWriteServiceClient) OpenDispute(ctx context.Context, in *v1.OpenDisputeRequest, opts ...grpc.CallOption) (*v1.OpenDisputeResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "OpenDispute", varargs...)
	ret0, _ := ret[0].(*v1.OpenDisputeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OpenDispute indicates an expected call of OpenDispute.
func (mr *MockOrderWriteServiceClientMockRecorder) OpenDispute(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OpenDispute", reflect.TypeOf((*MockOrderWriteServiceClient)(nil).OpenDispute), varargs...)
}

// RequestRevision mocks base method.
func (m *MockOrderWriteServiceClient) RequestRevision(ctx context.Context, in *v1.RequestRevisionRequest, opts ...grpc.CallOption) (*v1.RequestRevisionResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RequestRevision", varargs...)
	ret0, _ := ret[0].(*v1.RequestRevisionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RequestRevision indicates an expected call of RequestRevision.
func (mr *MockOrderWriteServiceClientMockRecorder) RequestRevision(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestRevision", reflect.TypeOf((*MockOrderWriteServiceClient)(nil).RequestRevision), varargs...)
}

// SaveBuyerInitialMessage mocks base method.
func (m *MockOrderWriteServiceClient) SaveBuyerInitialMessage(ctx context.Context, in *v1.SaveBuyerInitialMessageRequest, opts ...grpc.CallOption) (*v1.SaveBuyerInitialMessageResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SaveBuyerInitialMessage", varargs...)
	ret0, _ := ret[0].(*v1.SaveBuyerInitialMessageResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveBuyerInitialMessage indicates an expected call of SaveBuyerInitialMessage.
func (mr *MockOrderWriteServiceClientMockRecorder) SaveBuyerInitialMessage(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveBuyerInitialMessage", reflect.TypeOf((*MockOrderWriteServiceClient)(nil).SaveBuyerInitialMessage), varargs...)
}

// SaveDelivery mocks base method.
func (m *MockOrderWriteServiceClient) SaveDelivery(ctx context.Context, in *v1.SaveDeliveryRequest, opts ...grpc.CallOption) (*v1.SaveDeliveryResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SaveDelivery", varargs...)
	ret0, _ := ret[0].(*v1.SaveDeliveryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveDelivery indicates an expected call of SaveDelivery.
func (mr *MockOrderWriteServiceClientMockRecorder) SaveDelivery(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveDelivery", reflect.TypeOf((*MockOrderWriteServiceClient)(nil).SaveDelivery), varargs...)
}

// SaveRequirementAnswers mocks base method.
func (m *MockOrderWriteServiceClient) SaveRequirementAnswers(ctx context.Context, in *v1.SaveRequirementAnswersRequest, opts ...grpc.CallOption) (*v1.SaveRequirementAnswersResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SaveRequirementAnswers", varargs...)
	ret0, _ := ret[0].(*v1.SaveRequirementAnswersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveRequirementAnswers indicates an expected call of SaveRequirementAnswers.
func (mr *MockOrderWriteServiceClientMockRecorder) SaveRequirementAnswers(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveRequirementAnswers", reflect.TypeOf((*MockOrderWriteServiceClient)(nil).SaveRequirementAnswers), varargs...)
}

// MockOrderWriteServiceServer is a mock of OrderWriteServiceServer interface.
type MockOrderWriteServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockOrderWriteServiceServerMockRecorder
	isgomock struct{}
}

// MockOrderWriteServiceServerMockRecorder is the mock recorder for MockOrderWriteServiceServer.
type MockOrderWriteServiceServerMockRecorder struct {
	mock *MockOrderWriteServiceServer
}

// NewMockOrderWriteServiceServer creates a new mock instance.
func NewMockOrderWriteServiceServer(ctrl *gomock.Controller) *MockOrderWriteServiceServer {
	mock := &MockOrderWriteServiceServer{ctrl: ctrl}
	mock.recorder = &MockOrderWriteServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderWriteServiceServer) EXPECT() *MockOrderWriteServiceServerMockRecorder {
	return m.recorder
}

// AttachFileToOrder mocks base method.
func (m *MockOrderWriteServiceServer) AttachFileToOrder(arg0 context.Context, arg1 *v1.AttachFileToOrderRequest) (*v1.AttachFileToOrderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AttachFileToOrder", arg0, arg1)
	ret0, _ := ret[0].(*v1.AttachFileToOrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AttachFileToOrder indicates an expected call of AttachFileToOrder.
func (mr *MockOrderWriteServiceServerMockRecorder) AttachFileToOrder(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttachFileToOrder", reflect.TypeOf((*MockOrderWriteServiceServer)(nil).AttachFileToOrder), arg0, arg1)
}

// CreateDraftOrder mocks base method.
func (m *MockOrderWriteServiceServer) CreateDraftOrder(arg0 context.Context, arg1 *v1.CreateDraftOrderRequest) (*v1.CreateDraftOrderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDraftOrder", arg0, arg1)
	ret0, _ := ret[0].(*v1.CreateDraftOrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDraftOrder indicates an expected call of CreateDraftOrder.
func (mr *MockOrderWriteServiceServerMockRecorder) CreateDraftOrder(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDraftOrder", reflect.TypeOf((*MockOrderWriteServiceServer)(nil).CreateDraftOrder), arg0, arg1)
}

// GetOrderLifecycleSnapshot mocks base method.
func (m *MockOrderWriteServiceServer) GetOrderLifecycleSnapshot(arg0 context.Context, arg1 *v1.GetOrderLifecycleSnapshotRequest) (*v1.GetOrderLifecycleSnapshotResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderLifecycleSnapshot", arg0, arg1)
	ret0, _ := ret[0].(*v1.GetOrderLifecycleSnapshotResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderLifecycleSnapshot indicates an expected call of GetOrderLifecycleSnapshot.
func (mr *MockOrderWriteServiceServerMockRecorder) GetOrderLifecycleSnapshot(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderLifecycleSnapshot", reflect.TypeOf((*MockOrderWriteServiceServer)(nil).GetOrderLifecycleSnapshot), arg0, arg1)
}

// GetOrderPaymentSnapshot mocks base method.
func (m *MockOrderWriteServiceServer) GetOrderPaymentSnapshot(arg0 context.Context, arg1 *v1.GetOrderPaymentSnapshotRequest) (*v1.GetOrderPaymentSnapshotResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderPaymentSnapshot", arg0, arg1)
	ret0, _ := ret[0].(*v1.GetOrderPaymentSnapshotResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderPaymentSnapshot indicates an expected call of GetOrderPaymentSnapshot.
func (mr *MockOrderWriteServiceServerMockRecorder) GetOrderPaymentSnapshot(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderPaymentSnapshot", reflect.TypeOf((*MockOrderWriteServiceServer)(nil).GetOrderPaymentSnapshot), arg0, arg1)
}

// MarkOrderCompleted mocks base method.
func (m *MockOrderWriteServiceServer) MarkOrderCompleted(arg0 context.Context, arg1 *v1.MarkOrderCompletedRequest) (*v1.MarkOrderCompletedResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkOrderCompleted", arg0, arg1)
	ret0, _ := ret[0].(*v1.MarkOrderCompletedResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkOrderCompleted indicates an expected call of MarkOrderCompleted.
func (mr *MockOrderWriteServiceServerMockRecorder) MarkOrderCompleted(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkOrderCompleted", reflect.TypeOf((*MockOrderWriteServiceServer)(nil).MarkOrderCompleted), arg0, arg1)
}

// MarkOrderFunded mocks base method.
func (m *MockOrderWriteServiceServer) MarkOrderFunded(arg0 context.Context, arg1 *v1.MarkOrderFundedRequest) (*v1.MarkOrderFundedResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkOrderFunded", arg0, arg1)
	ret0, _ := ret[0].(*v1.MarkOrderFundedResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkOrderFunded indicates an expected call of MarkOrderFunded.
func (mr *MockOrderWriteServiceServerMockRecorder) MarkOrderFunded(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkOrderFunded", reflect.TypeOf((*MockOrderWriteServiceServer)(nil).MarkOrderFunded), arg0, arg1)
}

// MarkPaymentFailed mocks base method.
func (m *MockOrderWriteServiceServer) MarkPaymentFailed(arg0 context.Context, arg1 *v1.MarkPaymentFailedRequest) (*v1.MarkPaymentFailedResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkPaymentFailed", arg0, arg1)
	ret0, _ := ret[0].(*v1.MarkPaymentFailedResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkPaymentFailed indicates an expected call of MarkPaymentFailed.
func (mr *MockOrderWriteServiceServerMockRecorder) MarkPaymentFailed(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkPaymentFailed", reflect.TypeOf((*MockOrderWriteServiceServer)(nil).MarkPaymentFailed), arg0, arg1)
}

// MarkPaymentPending mocks base method.
func (m *MockOrderWriteServiceServer) MarkPaymentPending(arg0 context.Context, arg1 *v1.MarkPaymentPendingRequest) (*v1.MarkPaymentPendingResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkPaymentPending", arg0, arg1)
	ret0, _ := ret[0].(*v1.MarkPaymentPendingResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkPaymentPending indicates an expected call of MarkPaymentPending.
func (mr *MockOrderWriteServiceServerMockRecorder) MarkPaymentPending(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkPaymentPending", reflect.TypeOf((*MockOrderWriteServiceServer)(nil).MarkPaymentPending), arg0, arg1)
}

// MarkReleaseFailed mocks base method.
func (m *MockOrderWriteServiceServer) MarkReleaseFailed(arg0 context.Context, arg1 *v1.MarkReleaseFailedRequest) (*v1.MarkReleaseFailedResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkReleaseFailed", arg0, arg1)
	ret0, _ := ret[0].(*v1.MarkReleaseFailedResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkReleaseFailed indicates an expected call of MarkReleaseFailed.
func (mr *MockOrderWriteServiceServerMockRecorder) MarkReleaseFailed(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkReleaseFailed", reflect.TypeOf((*MockOrderWriteServiceServer)(nil).MarkReleaseFailed), arg0, arg1)
}

// MarkReleasePending mocks base method.
func (m *MockOrderWriteServiceServer) MarkReleasePending(arg0 context.Context, arg1 *v1.MarkReleasePendingRequest) (*v1.MarkReleasePendingResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkReleasePending", arg0, arg1)
	ret0, _ := ret[0].(*v1.MarkReleasePendingResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkReleasePending indicates an expected call of MarkReleasePending.
func (mr *MockOrderWriteServiceServerMockRecorder) MarkReleasePending(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkReleasePending", reflect.TypeOf((*MockOrderWriteServiceServer)(nil).MarkReleasePending), arg0, arg1)
}

// OpenDispute mocks base method.
func (m *MockOrderWriteServiceServer) OpenDispute(arg0 context.Context, arg1 *v1.OpenDisputeRequest) (*v1.OpenDisputeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OpenDispute", arg0, arg1)
	ret0, _ := ret[0].(*v1.OpenDisputeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OpenDispute indicates an expected call of OpenDispute.
func (mr *MockOrderWriteServiceServerMockRecorder) OpenDispute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OpenDispute", reflect.TypeOf((*MockOrderWriteServiceServer)(nil).OpenDispute), arg0, arg1)
}

// RequestRevision mocks base method.
func (m *MockOrderWriteServiceServer) RequestRevision(arg0 context.Context, arg1 *v1.RequestRevisionRequest) (*v1.RequestRevisionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestRevision", arg0, arg1)
	ret0, _ := ret[0].(*v1.RequestRevisionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RequestRevision indicates an expected call of RequestRevision.
func (mr *MockOrderWriteServiceServerMockRecorder) RequestRevision(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestRevision", reflect.TypeOf((*MockOrderWriteServiceServer)(nil).RequestRevision), arg0, arg1)
}

// SaveBuyerInitialMessage mocks base method.
func (m *MockOrderWriteServiceServer) SaveBuyerInitialMessage(arg0 context.Context, arg1 *v1.SaveBuyerInitialMessageRequest) (*v1.SaveBuyerInitialMessageResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveBuyerInitialMessage", arg0, arg1)
	ret0, _ := ret[0].(*v1.SaveBuyerInitialMessageResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveBuyerInitialMessage indicates an expected call of SaveBuyerInitialMessage.
func (mr *MockOrderWriteServiceServerMockRecorder) SaveBuyerInitialMessage(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveBuyerInitialMessage", reflect.TypeOf((*MockOrderWriteServiceServer)(nil).SaveBuyerInitialMessage), arg0, arg1)
}

// SaveDelivery mocks base method.
func (m *MockOrderWriteServiceServer) SaveDelivery(arg0 context.Context, arg1 *v1.SaveDeliveryRequest) (*v1.SaveDeliveryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveDelivery", arg0, arg1)
	ret0, _ := ret[0].(*v1.SaveDeliveryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveDelivery indicates an expected call of SaveDelivery.
func (mr *MockOrderWriteServiceServerMockRecorder) SaveDelivery(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveDelivery", reflect.TypeOf((*MockOrderWriteServiceServer)(nil).SaveDelivery), arg0, arg1)
}

// SaveRequirementAnswers mocks base method.
func (m *MockOrderWriteServiceServer) SaveRequirementAnswers(arg0 context.Context, arg1 *v1.SaveRequirementAnswersRequest) (*v1.SaveRequirementAnswersResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveRequirementAnswers", arg0, arg1)
	ret0, _ := ret[0].(*v1.SaveRequirementAnswersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveRequirementAnswers indicates an expected call of SaveRequirementAnswers.
func (mr *MockOrderWriteServiceServerMockRecorder) SaveRequirementAnswers(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveRequirementAnswers", reflect.TypeOf((*MockOrderWriteServiceServer)(nil).SaveRequirementAnswers), arg0, arg1)
}

// MockUnsafeOrderWriteServiceServer is a mock of UnsafeOrderWriteServiceServer interface.
type MockUnsafeOrderWriteServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeOrderWriteServiceServerMockRecorder
	isgomock struct{}
}

// MockUnsafeOrderWriteServiceServerMockRecorder is the mock recorder for MockUnsafeOrderWriteServiceServer.
type MockUnsafeOrderWriteServiceServerMockRecorder struct {
	mock *MockUnsafeOrderWriteServiceServer
}

// NewMockUnsafeOrderWriteServiceServer creates a new mock instance.
func NewMockUnsafeOrderWriteServiceServer(ctrl *gomock.Controller) *MockUnsafeOrderWriteServiceServer {
	mock := &MockUnsafeOrderWriteServiceServer{ctrl: ctrl}
	mock.recorder = &MockUnsafeOrderWriteServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeOrderWriteServiceServer) EXPECT() *MockUnsafeOrderWriteServiceServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedOrderWriteServiceServer mocks base method.
func (m *MockUnsafeOrderWriteServiceServer) mustEmbedUnimplementedOrderWriteServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedOrderWriteServiceServer")
}

// mustEmbedUnimplementedOrderWriteServiceServer indicates an expected call of mustEmbedUnimplementedOrderWriteServiceServer.
func (mr *MockUnsafeOrderWriteServiceServerMockRecorder) mustEmbedUnimplementedOrderWriteServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedOrderWriteServiceServer", reflect.TypeOf((*MockUnsafeOrderWriteServiceServer)(nil).mustEmbedUnimplementedOrderWriteServiceServer))
}
