// Code generated by MockGen. DO NOT EDIT.
// Source: ../ofm-common/proto/paymentconnect/v1/paymentconnect_grpc.pb.go
//
// Generated by this command:
//
//	mockgen -source=../ofm-common/proto/paymentconnect/v1/paymentconnect_grpc.pb.go -destination=internal/infra/payment/grpc/paymentconnect_client_mock_test.go -package=grpc
//

// Package grpc is a generated GoMock package.
package grpc

import (
	context "context"
	reflect "reflect"

	v1 "github.com/ofm-microservices/ofm-common/proto/paymentconnect/v1"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockPaymentOnboardingServiceClient is a mock of PaymentOnboardingServiceClient interface.
type MockPaymentOnboardingServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentOnboardingServiceClientMockRecorder
	isgomock struct{}
}

// MockPaymentOnboardingServiceClientMockRecorder is the mock recorder for MockPaymentOnboardingServiceClient.
type MockPaymentOnboardingServiceClientMockRecorder struct {
	mock *MockPaymentOnboardingServiceClient
}

// NewMockPaymentOnboardingServiceClient creates a new mock instance.
func NewMockPaymentOnboardingServiceClient(ctrl *gomock.Controller) *MockPaymentOnboardingServiceClient {
	mock := &MockPaymentOnboardingServiceClient{ctrl: ctrl}
	mock.recorder = &MockPaymentOnboardingServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentOnboardingServiceClient) EXPECT() *MockPaymentOnboardingServiceClientMockRecorder {
	return m.recorder
}

// GetConnectStatus mocks base method.
func (m *MockPaymentOnboardingServiceClient) GetConnectStatus(ctx context.Context, in *v1.GetConnectStatusRequest, opts ...grpc.CallOption) (*v1.GetConnectStatusResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetConnectStatus", varargs...)
	ret0, _ := ret[0].(*v1.GetConnectStatusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConnectStatus indicates an expected call of GetConnectStatus.
func (mr *MockPaymentOnboardingServiceClientMockRecorder) GetConnectStatus(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConnectStatus", reflect.TypeOf((*MockPaymentOnboardingServiceClient)(nil).GetConnectStatus), varargs...)
}

// StartFreelancerOnboarding mocks base method.
func (m *MockPaymentOnboardingServiceClient) StartFreelancerOnboarding(ctx context.Context, in *v1.StartFreelancerOnboardingRequest, opts ...grpc.CallOption) (*v1.StartFreelancerOnboardingResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "StartFreelancerOnboarding", varargs...)
	ret0, _ := ret[0].(*v1.StartFreelancerOnboardingResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartFreelancerOnboarding indicates an expected call of StartFreelancerOnboarding.
func (mr *MockPaymentOnboardingServiceClientMockRecorder) StartFreelancerOnboarding(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartFreelancerOnboarding", reflect.TypeOf((*MockPaymentOnboardingServiceClient)(nil).StartFreelancerOnboarding), varargs...)
}

// MockPaymentOnboardingServiceServer is a mock of PaymentOnboardingServiceServer interface.
type MockPaymentOnboardingServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentOnboardingServiceServerMockRecorder
	isgomock struct{}
}

// MockPaymentOnboardingServiceServerMockRecorder is the mock recorder for MockPaymentOnboardingServiceServer.
type MockPaymentOnboardingServiceServerMockRecorder struct {
	mock *MockPaymentOnboardingServiceServer
}

// NewMockPaymentOnboardingServiceServer creates a new mock instance.
func NewMockPaymentOnboardingServiceServer(ctrl *gomock.Controller) *MockPaymentOnboardingServiceServer {
	mock := &MockPaymentOnboardingServiceServer{ctrl: ctrl}
	mock.recorder = &MockPaymentOnboardingServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentOnboardingServiceServer) EXPECT() *MockPaymentOnboardingServiceServerMockRecorder {
	return m.recorder
}

// GetConnectStatus mocks base method.
func (m *MockPaymentOnboardingServiceServer) GetConnectStatus(arg0 context.Context, arg1 *v1.GetConnectStatusRequest) (*v1.GetConnectStatusResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConnectStatus", arg0, arg1)
	ret0, _ := ret[0].(*v1.GetConnectStatusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConnectStatus indicates an expected call of GetConnectStatus.
func (mr *MockPaymentOnboardingServiceServerMockRecorder) GetConnectStatus(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConnectStatus", reflect.TypeOf((*MockPaymentOnboardingServiceServer)(nil).GetConnectStatus), arg0, arg1)
}

// StartFreelancerOnboarding mocks base method.
func (m *MockPaymentOnboardingServiceServer) StartFreelancerOnboarding(arg0 context.Context, arg1 *v1.StartFreelancerOnboardingRequest) (*v1.StartFreelancerOnboardingResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartFreelancerOnboarding", arg0, arg1)
	ret0, _ := ret[0].(*v1.StartFreelancerOnboardingResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartFreelancerOnboarding indicates an expected call of StartFreelancerOnboarding.
func (mr *MockPaymentOnboardingServiceServerMockRecorder) StartFreelancerOnboarding(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartFreelancerOnboarding", reflect.TypeOf((*MockPaymentOnboardingServiceServer)(nil).StartFreelancerOnboarding), arg0, arg1)
}

// MockUnsafePaymentOnboardingServiceServer is a mock of UnsafePaymentOnboardingServiceServer interface.
type MockUnsafePaymentOnboardingServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafePaymentOnboardingServiceServerMockRecorder
	isgomock struct{}
}

// MockUnsafePaymentOnboardingServiceServerMockRecorder is the mock recorder for MockUnsafePaymentOnboardingServiceServer.
type MockUnsafePaymentOnboardingServiceServerMockRecorder struct {
	mock *MockUnsafePaymentOnboardingServiceServer
}

// NewMockUnsafePaymentOnboardingServiceServer creates a new mock instance.
func NewMockUnsafePaymentOnboardingServiceServer(ctrl *gomock.Controller) *MockUnsafePaymentOnboardingServiceServer {
	mock := &MockUnsafePaymentOnboardingServiceServer{ctrl: ctrl}
	mock.recorder = &MockUnsafePaymentOnboardingServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafePaymentOnboardingServiceServer) EXPECT() *MockUnsafePaymentOnboardingServiceServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedPaymentOnboardingServiceServer mocks base method.
func (m *MockUnsafePaymentOnboardingServiceServer) mustEmbedUnimplementedPaymentOnboardingServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedPaymentOnboardingServiceServer")
}

// mustEmbedUnimplementedPaymentOnboardingServiceServer indicates an expected call of mustEmbedUnimplementedPaymentOnboardingServiceServer.
func (mr *MockUnsafePaymentOnboardingServiceServerMockRecorder) mustEmbedUnimplementedPaymentOnboardingServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedPaymentOnboardingServiceServer", reflect.TypeOf((*MockUnsafePaymentOnboardingServiceServer)(nil).mustEmbedUnimplementedPaymentOnboardingServiceServer))
}
