// Code generated by MockGen. DO NOT EDIT.
// Source: ../ofm-common/proto/paymentcheckout/v1/paymentcheckout_grpc.pb.go
//
// Generated by this command:
//
//	mockgen -source=../ofm-common/proto/paymentcheckout/v1/paymentcheckout_grpc.pb.go -destination=internal/infra/payment/grpc/paymentcheckout_client_mock_test.go -package=grpc
//

// Package grpc is a generated GoMock package.
package grpc

import (
	context "context"
	reflect "reflect"

	v1 "github.com/ofm-microservices/ofm-common/proto/paymentcheckout/v1"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockPaymentCheckoutServiceClient is a mock of PaymentCheckoutServiceClient interface.
type MockPaymentCheckoutServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentCheckoutServiceClientMockRecorder
	isgomock struct{}
}

// MockPaymentCheckoutServiceClientMockRecorder is the mock recorder for MockPaymentCheckoutServiceClient.
type MockPaymentCheckoutServiceClientMockRecorder struct {
	mock *MockPaymentCheckoutServiceClient
}

// NewMockPaymentCheckoutServiceClient creates a new mock instance.
func NewMockPaymentCheckoutServiceClient(ctrl *gomock.Controller) *MockPaymentCheckoutServiceClient {
	mock := &MockPaymentCheckoutServiceClient{ctrl: ctrl}
	mock.recorder = &MockPaymentCheckoutServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentCheckoutServiceClient) EXPECT() *MockPaymentCheckoutServiceClientMockRecorder {
	return m.recorder
}

// CreateCheckoutSession mocks base method.
func (m *MockPaymentCheckoutServiceClient) CreateCheckoutSession(ctx context.Context, in *v1.CreateCheckoutSessionRequest, opts ...grpc.CallOption) (*v1.CreateCheckoutSessionResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateCheckoutSession", varargs...)
	ret0, _ := ret[0].(*v1.CreateCheckoutSessionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCheckoutSession indicates an expected call of CreateCheckoutSession.
func (mr *MockPaymentCheckoutServiceClientMockRecorder) CreateCheckoutSession(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCheckoutSession", reflect.TypeOf((*MockPaymentCheckoutServiceClient)(nil).CreateCheckoutSession), varargs...)
}

// GetReleaseByOrderId mocks base method.
func (m *MockPaymentCheckoutServiceClient) GetReleaseByOrderId(ctx context.Context, in *v1.GetReleaseByOrderIdRequest, opts ...grpc.CallOption) (*v1.GetReleaseByOrderIdResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetReleaseByOrderId", varargs...)
	ret0, _ := ret[0].(*v1.GetReleaseByOrderIdResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReleaseByOrderId indicates an expected call of GetReleaseByOrderId.
func (mr *MockPaymentCheckoutServiceClientMockRecorder) GetReleaseByOrderId(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReleaseByOrderId", reflect.TypeOf((*MockPaymentCheckoutServiceClient)(nil).GetReleaseByOrderId), varargs...)
}

// ReleaseFunds mocks base method.
func (m *MockPaymentCheckoutServiceClient) ReleaseFunds(ctx context.Context, in *v1.ReleaseFundsRequest, opts ...grpc.CallOption) (*v1.ReleaseFundsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ReleaseFunds", varargs...)
	ret0, _ := ret[0].(*v1.ReleaseFundsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReleaseFunds indicates an expected call of ReleaseFunds.
func (mr *MockPaymentCheckoutServiceClientMockRecorder) ReleaseFunds(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseFunds", reflect.TypeOf((*MockPaymentCheckoutServiceClient)(nil).ReleaseFunds), varargs...)
}

// MockPaymentCheckoutServiceServer is a mock of PaymentCheckoutServiceServer interface.
type MockPaymentCheckoutServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentCheckoutServiceServerMockRecorder
	isgomock struct{}
}

// MockPaymentCheckoutServiceServerMockRecorder is the mock recorder for MockPaymentCheckoutServiceServer.
type MockPaymentCheckoutServiceServerMockRecorder struct {
	mock *MockPaymentCheckoutServiceServer
}

// NewMockPaymentCheckoutServiceServer creates a new mock instance.
func NewMockPaymentCheckoutServiceServer(ctrl *gomock.Controller) *MockPaymentCheckoutServiceServer {
	mock := &MockPaymentCheckoutServiceServer{ctrl: ctrl}
	mock.recorder = &MockPaymentCheckoutServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentCheckoutServiceServer) EXPECT() *MockPaymentCheckoutServiceServerMockRecorder {
	return m.recorder
}

// CreateCheckoutSession mocks base method.
func (m *MockPaymentCheckoutServiceServer) CreateCheckoutSession(arg0 context.Context, arg1 *v1.CreateCheckoutSessionRequest) (*v1.CreateCheckoutSessionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCheckoutSession", arg0, arg1)
	ret0, _ := ret[0].(*v1.CreateCheckoutSessionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCheckoutSession indicates an expected call of CreateCheckoutSession.
func (mr *MockPaymentCheckoutServiceServerMockRecorder) CreateCheckoutSession(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCheckoutSession", reflect.TypeOf((*MockPaymentCheckoutServiceServer)(nil).CreateCheckoutSession), arg0, arg1)
}

// GetReleaseByOrderId mocks base method.
func (m *MockPaymentCheckoutServiceServer) GetReleaseByOrderId(arg0 context.Context, arg1 *v1.GetReleaseByOrderIdRequest) (*v1.GetReleaseByOrderIdResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReleaseByOrderId", arg0, arg1)
	ret0, _ := ret[0].(*v1.GetReleaseByOrderIdResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReleaseByOrderId indicates an expected call of GetReleaseByOrderId.
func (mr *MockPaymentCheckoutServiceServerMockRecorder) GetReleaseByOrderId(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReleaseByOrderId", reflect.TypeOf((*MockPaymentCheckoutServiceServer)(nil).GetReleaseByOrderId), arg0, arg1)
}

// ReleaseFunds mocks base method.
func (m *MockPaymentCheckoutServiceServer) ReleaseFunds(arg0 context.Context, arg1 *v1.ReleaseFundsRequest) (*v1.ReleaseFundsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseFunds", arg0, arg1)
	ret0, _ := ret[0].(*v1.ReleaseFundsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReleaseFunds indicates an expected call of ReleaseFunds.
func (mr *MockPaymentCheckoutServiceServerMockRecorder) ReleaseFunds(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseFunds", reflect.TypeOf((*MockPaymentCheckoutServiceServer)(nil).ReleaseFunds), arg0, arg1)
}

// MockUnsafePaymentCheckoutServiceServer is a mock of UnsafePaymentCheckoutServiceServer interface.
type MockUnsafePaymentCheckoutServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafePaymentCheckoutServiceServerMockRecorder
	isgomock struct{}
}

// MockUnsafePaymentCheckoutServiceServerMockRecorder is the mock recorder for MockUnsafePaymentCheckoutServiceServer.
type MockUnsafePaymentCheckoutServiceServerMockRecorder struct {
	mock *MockUnsafePaymentCheckoutServiceServer
}

// NewMockUnsafePaymentCheckoutServiceServer creates a new mock instance.
func NewMockUnsafePaymentCheckoutServiceServer(ctrl *gomock.Controller) *MockUnsafePaymentCheckoutServiceServer {
	mock := &MockUnsafePaymentCheckoutServiceServer{ctrl: ctrl}
	mock.recorder = &MockUnsafePaymentCheckoutServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafePaymentCheckoutServiceServer) EXPECT() *MockUnsafePaymentCheckoutServiceServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedPaymentCheckoutServiceServer mocks base method.
func (m *MockUnsafePaymentCheckoutServiceServer) mustEmbedUnimplementedPaymentCheckoutServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedPaymentCheckoutServiceServer")
}

// mustEmbedUnimplementedPaymentCheckoutServiceServer indicates an expected call of mustEmbedUnimplementedPaymentCheckoutServiceServer.
func (mr *MockUnsafePaymentCheckoutServiceServerMockRecorder) mustEmbedUnimplementedPaymentCheckoutServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedPaymentCheckoutServiceServer", reflect.TypeOf((*MockUnsafePaymentCheckoutServiceServer)(nil).mustEmbedUnimplementedPaymentCheckoutServiceServer))
}
